### ISSUE TITLE
Thesis and papers

### ISSUE THREAD

**Issue by Augusto-Gomez-Eguiluz** [linchangyi1/Awesome-Touch#13]
**PhD Thesis**

https://scholar.google.com/citations?view_op=view_citation&hl=en&user=1PbAJlEAAAAJ&cstart=20&pagesize=80&sortby=pubdate&citation_for_view=1PbAJlEAAAAJ:qUcmZB5y_30C

**Papers using BioTAC:**

https://scholar.google.com/citations?view_op=view_citation&hl=en&user=1PbAJlEAAAAJ&cstart=20&pagesize=80&sortby=pubdate&citation_for_view=1PbAJlEAAAAJ:u5HHmVD_uO8C

https://scholar.google.com/citations?view_op=view_citation&hl=en&user=1PbAJlEAAAAJ&cstart=20&pagesize=80&sortby=pubdate&citation_for_view=1PbAJlEAAAAJ:u-x6o8ySG0sC

https://scholar.google.com/citations?view_op=view_citation&hl=en&user=1PbAJlEAAAAJ&cstart=20&pagesize=80&sortby=pubdate&citation_for_view=1PbAJlEAAAAJ:Y0pCki6q_DkC

https://scholar.google.com/citations?view_op=view_citation&hl=en&user=1PbAJlEAAAAJ&sortby=pubdate&citation_for_view=1PbAJlEAAAAJ:WF5omc3nYNoC

https://scholar.google.com/citations?view_op=view_citation&hl=en&user=1PbAJlEAAAAJ&sortby=pubdate&citation_for_view=1PbAJlEAAAAJ:Se3iqnhoufwC

https://scholar.google.com/citations?view_op=view_citation&hl=en&user=1PbAJlEAAAAJ&sortby=pubdate&citation_for_view=1PbAJlEAAAAJ:mVmsd5A6BfQC

**Comment by linchangyi1** [comment]
Thanks a lot~
