### ISSUE TITLE
adding recognition works

### ISSUE THREAD

**Issue by jingxixu** [linchangyi1/Awesome-Touch#2]
Thanks for making this exciting repo!

Is it possible to include [TANDEM (RA-L 2022/IROS 2022)](https://jxu.ai/tandem/) and [TANDEM3D (ICRA 2023)](https://jxu.ai/tandem3d/) in the Classification/Recognition? Many thanks!

**Comment by linchangyi1** [comment]
Of course! And thanks for your kind remind. Cool works!
