### ISSUE TITLE
关于老化的问题

### ISSUE THREAD

**Issue by elevenjiang1** [linchangyi1/Awesome-Touch#3]
您好，很高兴能阅读到您的论文，最近在打算复现一个
不过有一个关于tactile老化的问题，想了解一下您有测试过如果进行了长时间的接触任务后(如多次按压/甚至一些Pushing方面的工作)，摄像头以同样的力接触一个物体，拍摄到的图像是否会改变？tactile的3D重建效果是否依旧可以用最开始标定的参数?

**Comment by linchangyi1** [comment]
你好，摄像头拍摄到的图像基本取决于光照和硅胶的形变，灯光应该可以维持稳定。长时间接触后，硅胶可能会有小量的残余形变（描述可能不准确），这会使得离开接触物体后，在没有物体接触的情况下深度图像会有少量的噪点。不过当传感器再次与物体接触时，如果形变还是和上次接触一样，我认为得到的图像会和上次的基本一致（不考虑图像噪声的正常出现）。但是对于你提到的”同样的力“接触，我不太确定”同样的力“是否会导致”同样的形变“，如果是的话那可以认为图像的变化不大。

对于是否需要重新标定的问题。我认为如果环境和内部的灯光都比较稳定，可以不需要再次标定。所以，为了让内部的灯光在每一次使用传感器时趋于相似，最好是每一次先打开灯光，再打开摄像头，并且等摄像头的图像比较稳定后再获取reference image来使用传感器（具体可以看DTact的源码）。

btw,似乎这个问题在https://github.com/linchangyi1/DTact提更好哈。

**Comment by elevenjiang1** [comment]
不好意思，我的失误，后续问题已在DTact上进行提问
谢谢您的回答~
